"""Setup guides for apps people ask Echo to work with (agent/integrations.py).

The official MCP registry lists thousands of servers, matched by name only, with
official and third-party entries side by side. These guides cover apps across
different kinds of work with what the registry can't say: the steps inside the
app, what the server can do that deserves care, and how to check it works.

Each guide names its server the way it is installed. The version is looked up
when the connection is proposed and pinned there, so an approved connection
never updates itself.

how:
  {"kind": "npm" | "pypi", "package": ...}       a local program run by npx / uvx
  {"kind": "http", "url": ...}                     a server the app itself runs (or a hosted one)
  {"kind": "signin", "url": ...}                   hosted, but needs browser sign-in EchoSpeak can't do yet
  {"kind": "builtin", "where": ...}                EchoSpeak already has this connection

Researched October 2026 from each project's own page and the registry. Steps
inside third-party apps change; the homepage link is the source of truth.
"""

from __future__ import annotations

from typing import Any

# Settings a connection may need. "secret" ones are stored encrypted (Windows DPAPI)
# and are only ever typed by the user in Settings, never by an agent.
GUIDES: list[dict[str, Any]] = [
    # ── creative & media ──────────────────────────────────────────────
    {
        "id": "blender",
        "app": "Blender",
        "field": "3D modeling and animation",
        "keywords": ["blender", "3d", "modeling", "modelling", "render", "animation", "mesh"],
        "publisher": "community (ahujasid/blender-mcp, the most used Blender server)",
        "how": {"kind": "pypi", "package": "mcp-for-blender"},
        "needs": ["uv", "Blender 3.0 or newer"],
        "settings": [
            {"name": "BLENDER_MCP_SAFE_MODE", "secret": False, "required": False, "default": "1",
             "about": "1 makes the add-on check scripts before they run and block risky code."},
        ],
        "steps": [
            "Install the Blender add-on: run `uvx mcp-for-blender install-addon` (or install addon.py from the project page).",
            "In Blender: Edit > Preferences > Add-ons, enable \"Interface: MCP for Blender\".",
            "In the 3D Viewport press N, open the MCP for Blender tab and click Start MCP Server (it listens on localhost:9876).",
        ],
        "watch_out": [
            "execute_blender_code runs any Python inside Blender: save your work first. EchoSpeak asks before each run.",
            "The add-on's socket has no password; keep it on this PC (localhost).",
        ],
        "verify": "Ask for the scene info (a read-only tool) and check the objects match what is open in Blender.",
        "capability_policies": {"execute_blender_code": "destructive"},
        "homepage": "https://github.com/ahujasid/blender-mcp",
    },
    {
        "id": "photoshop",
        "app": "Adobe Photoshop",
        "field": "photo editing and graphic design",
        "keywords": ["photoshop", "psd", "photo", "retouch", "adobe", "layers"],
        "publisher": "community (not made or endorsed by Adobe)",
        "how": {"kind": "npm", "package": "@alisaitteke/photoshop-mcp",
                "registry": "io.github.alisaitteke/photoshop-mcp"},
        "needs": ["Node.js 18 or newer", "Photoshop running on this PC"],
        "settings": [],
        "steps": [
            "Open Photoshop before using it; the server talks to the running app.",
            "If its tools say Photoshop isn't reachable, follow the project page for the Photoshop plugin step.",
        ],
        "watch_out": [
            "Collects anonymous usage analytics by default; the project page says how to turn that off.",
            "Leave TYPESAFE_API_KEY unset: setting it sends prompts to api.typesafe.ai.",
            "Generative fill needs your Adobe account.",
        ],
        "verify": "List the open documents and layers, then compare with Photoshop.",
        "capability_policies": {},
        "homepage": "https://github.com/alisaitteke/photoshop-mcp",
    },
    {
        "id": "premiere",
        "app": "Adobe Premiere Pro",
        "field": "video editing",
        "keywords": ["premiere", "video", "edit", "editing", "timeline", "adobe", "sequence"],
        "publisher": "community (not made or endorsed by Adobe)",
        "how": {"kind": "npm", "package": "premiere-pro-mcp", "registry": "io.github.leancoderkavy/premiere-pro"},
        "needs": ["Node.js 20.19 or newer", "Premiere Pro 2020-2026", "FFmpeg (only for trim, slip and silence tools)"],
        "settings": [],
        "steps": [
            "Install its Premiere panel: run `npx premiere-pro-mcp --install-cep`. This turns on Adobe's PlayerDebugMode setting so unsigned panels load; the project page explains it.",
            "Restart Premiere and open a copy of a project with an active sequence.",
            "Open Window > Extensions > MCP for Adobe Premiere Pro and check it says Running.",
        ],
        "watch_out": [
            "Work on a copy of the project at first; some Premiere 26.x builds ignore certain edits.",
            "Clip speed and direction can't be changed through scripting.",
        ],
        "verify": "Run verify_premiere_connection, then get_capabilities.",
        "capability_policies": {},
        "homepage": "https://github.com/leancoderkavy/premiere-pro-mcp",
    },
    {
        "id": "figma",
        "app": "Figma",
        "field": "UI and product design",
        "keywords": ["figma", "design", "ui", "ux", "mockup", "prototype", "wireframe"],
        "publisher": "official (Figma)",
        "how": {"kind": "http", "url": "http://127.0.0.1:3845/mcp"},
        "needs": ["Figma desktop app"],
        "settings": [],
        "steps": [
            "Open a design file in the Figma desktop app with nothing selected and switch to Dev Mode.",
            "Enable the desktop MCP server in the right sidebar (newer versions: Ctrl+K, search \"Enable desktop MCP server\").",
        ],
        "watch_out": [
            "Figma's hosted server (mcp.figma.com) can also edit the canvas, but needs a browser sign-in EchoSpeak doesn't support yet.",
        ],
        "verify": "Ask for the design context of the selected frame.",
        "capability_policies": {},
        "homepage": "https://help.figma.com/hc/en-us/articles/35281186390679",
    },
    {
        "id": "obs",
        "app": "OBS Studio",
        "field": "streaming and screen recording",
        "keywords": ["obs", "stream", "streaming", "recording", "scene", "twitch", "broadcast"],
        "publisher": "community (royshil/obs-mcp)",
        "how": {"kind": "npm", "package": "obs-mcp"},
        "needs": ["Node.js", "OBS Studio 31 or newer"],
        "settings": [
            {"name": "OBS_WEBSOCKET_URL", "secret": False, "required": False, "default": "ws://localhost:4455",
             "about": "OBS's WebSocket address."},
            {"name": "OBS_WEBSOCKET_PASSWORD", "secret": True, "required": True,
             "about": "The password from OBS > Tools > WebSocket Server Settings."},
        ],
        "steps": [
            "In OBS: Tools > WebSocket Server Settings, enable the server and set a password.",
            "Paste that password here when you approve.",
        ],
        "watch_out": ["It can start and stop streams and recordings; EchoSpeak asks before those actions."],
        "verify": "List the scenes and compare with OBS.",
        "capability_policies": {},
        "homepage": "https://github.com/royshil/obs-mcp",
    },
    {
        "id": "ableton",
        "app": "Ableton Live",
        "field": "music production",
        "keywords": ["ableton", "music", "daw", "midi", "track", "beat", "audio"],
        "publisher": "community",
        "how": {"kind": "pypi", "package": "mcp-server-ableton-live", "registry": "io.github.wstierhout/ableton-live-mcp"},
        "needs": ["uv", "Ableton Live"],
        "settings": [],
        "steps": ["Follow the project page for the part inside Ableton (its control surface script), then restart Live."],
        "watch_out": ["Save your set first; tools change tracks and clips directly."],
        "verify": "Ask for the tempo and track list and compare with Live.",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.wstierhout%2Fableton-live-mcp/versions/latest",
    },
    # ── game development ──────────────────────────────────────────────
    {
        "id": "godot",
        "app": "Godot",
        "field": "game development",
        "keywords": ["godot", "game", "gdscript", "gamedev", "engine"],
        "publisher": "community",
        "how": {"kind": "npm", "package": "godot-mcp-runtime", "registry": "io.github.Erodenn/godot-mcp-runtime"},
        "needs": ["Node.js", "Godot 4"],
        "settings": [],
        "steps": ["No add-on needed. If it can't find Godot, follow the project page to point it at Godot."],
        "watch_out": ["It can run your game and edit project files; keep the project in git."],
        "verify": "Ask it for the project's scenes.",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.Erodenn%2Fgodot-mcp-runtime/versions/latest",
    },
    {
        "id": "unreal",
        "app": "Unreal Engine",
        "field": "game development and virtual production",
        "keywords": ["unreal", "ue5", "blueprint", "game", "engine", "level"],
        "publisher": "community (beta)",
        "how": {"kind": "npm", "package": "unreal-engine-mcp-server", "registry": "io.github.ChiR24/unreal-engine-mcp"},
        "needs": ["Node.js", "Unreal Engine 5"],
        "settings": [],
        "steps": ["Follow the project page for the plugins to enable inside the Unreal Editor, then restart the editor."],
        "watch_out": ["Beta: save and commit the project before letting it change levels or Blueprints."],
        "verify": "Ask for the actors in the open level.",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.ChiR24%2Funreal-engine-mcp/versions/latest",
    },
    # ── engineering ───────────────────────────────────────────────────
    {
        "id": "kicad",
        "app": "KiCad",
        "field": "electronics and PCB design",
        "keywords": ["kicad", "pcb", "schematic", "electronics", "circuit", "eda"],
        "publisher": "community",
        "how": {"kind": "pypi", "package": "kicad-mcp-server", "registry": "io.github.bunnyf/kicad-mcp-server"},
        "needs": ["uv", "KiCad 9"],
        "settings": [],
        "steps": ["Follow the project page if it asks where KiCad or your projects are."],
        "watch_out": ["Keep board files in git; it edits schematics and layouts in place."],
        "verify": "Ask it to list the components of a project.",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.bunnyf%2Fkicad-mcp-server/versions/latest",
    },
    {
        "id": "autocad",
        "app": "AutoCAD",
        "field": "CAD and drafting",
        "keywords": ["autocad", "cad", "dwg", "drafting", "drawing"],
        "publisher": "community (early version)",
        "how": {"kind": "npm", "package": "@dmytro-prototypes/cadbridge-mcp",
                "registry": "net.dmytro-prototypes/cadbridge-mcp-autocad"},
        "needs": ["Node.js", "AutoCAD running on this PC"],
        "settings": [],
        "steps": ["Follow the project page for the part inside AutoCAD."],
        "watch_out": ["Early release: work on a copy of the drawing."],
        "verify": "Ask for the layers of the open drawing.",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/net.dmytro-prototypes%2Fcadbridge-mcp-autocad/versions/latest",
    },
    # ── software development & data ───────────────────────────────────
    {
        "id": "github",
        "app": "GitHub",
        "field": "software development",
        "keywords": ["github", "repo", "repository", "pull", "issues", "git"],
        "publisher": "official (GitHub)",
        "how": {"kind": "http", "url": "https://api.githubcopilot.com/mcp/"},
        "needs": [],
        "settings": [
            {"name": "Authorization", "kind": "header", "secret": True, "required": True, "template": "Bearer {value}",
             "about": "A fine-grained personal access token (github.com > Settings > Developer settings). Give it only the repositories and permissions you want Echo to have."},
        ],
        "steps": ["Create a fine-grained token limited to the repositories you want, and paste it when you approve."],
        "watch_out": ["Echo can do whatever the token allows; read-only permissions are a good start."],
        "verify": "Ask for your recent repositories.",
        "capability_policies": {},
        "homepage": "https://docs.github.com/en/copilot/how-tos/provide-context/use-mcp/use-the-github-mcp-server",
    },
    {
        "id": "playwright",
        "app": "Web browser automation (Playwright)",
        "field": "testing and web automation",
        "keywords": ["playwright", "browser", "chrome", "automate", "website", "testing", "scrape"],
        "publisher": "official (Microsoft)",
        "how": {"kind": "npm", "package": "@playwright/mcp", "registry": "io.github.microsoft/playwright-mcp"},
        "needs": ["Node.js"],
        "settings": [],
        "steps": ["The first run downloads a browser, which takes a minute."],
        "watch_out": ["It drives a real browser: pages it opens are outside content, and form submits ask first."],
        "verify": "Open example.com and read the heading.",
        "capability_policies": {},
        "homepage": "https://github.com/microsoft/playwright-mcp",
    },
    {
        "id": "jupyter",
        "app": "Jupyter notebooks",
        "field": "data science",
        "keywords": ["jupyter", "notebook", "ipynb", "data", "pandas", "analysis"],
        "publisher": "community",
        "how": {"kind": "pypi", "package": "better-jupyter-mcp-server", "registry": "io.github.ChengJiale150/jupyter-mcp-server"},
        "needs": ["uv", "Jupyter"],
        "settings": [],
        "steps": ["Follow the project page to point it at your Jupyter server or notebooks."],
        "watch_out": ["Running cells runs code on this PC; EchoSpeak asks first."],
        "verify": "List the cells of a notebook.",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.ChengJiale150%2Fjupyter-mcp-server/versions/latest",
    },
    {
        "id": "rea",
        "app": "REA (reverse engineering)",
        "field": "reverse engineering and security research",
        "keywords": ["rea", "reverse", "engineer", "engineering", "decompile", "decompiler", "disassemble", "binary",
                     "ghidra", "ida", "hopper", "electron", "asar", "malware", "ctf", "exe", "dll"],
        "publisher": "community (morluto/rea, MIT, 23k stars)",
        "how": {"kind": "npm", "package": "rea-agents", "registry": "io.github.morluto/rea"},
        "needs": ["Node.js 22.19 or newer", "Ghidra or IDA only for native .exe/.dll analysis (Windows Ghidra support is experimental)"],
        "settings": [
            {"name": "GHIDRA_INSTALL_DIR", "secret": False, "required": False,
             "about": "Your Ghidra folder, only for native binaries. REA never installs or changes Ghidra."},
            {"name": "JAVA_HOME", "secret": False, "required": False, "about": "The JDK Ghidra uses, if it isn't found on its own."},
        ],
        "steps": [
            "Nothing else for JavaScript/Electron apps, .NET assemblies, packages, websites and HAR captures.",
            "For native .exe/.dll analysis, install Ghidra yourself and fill in GHIDRA_INSTALL_DIR.",
            "Don't run `rea-agents setup`: it registers REA with other agents (Claude Code, Codex...), not EchoSpeak.",
        ],
        "watch_out": [
            "Only analyze software you're allowed to; REA's license is for lawful research.",
            "Not a sandbox: an untrusted binary is parsed by Ghidra with your Windows permissions.",
            "EchoSpeak trusts REA's own effect labels here: analysis that only adds to REA's notes runs without asking; "
            "anything that launches the target, uses the network, writes files or may discard data still asks.",
            "Tools that run the target app (capture_*_scenario, observe_native_calls) really run it.",
        ],
        "verify": "Call binary_session with {}: it lists every REA tool and whether it works on this PC.",
        "capability_policies": {},
        "timeout_s": 300,
        "accept_server_read_only_hints": True,
        "homepage": "https://github.com/morluto/rea",
    },
    # ── business ──────────────────────────────────────────────────────
    {
        "id": "stripe",
        "app": "Stripe",
        "field": "payments and billing",
        "keywords": ["stripe", "payments", "invoice", "billing", "subscription", "refund", "customers"],
        "publisher": "official (Stripe)",
        "how": {"kind": "http", "url": "https://mcp.stripe.com"},
        "needs": [],
        "settings": [
            {"name": "Authorization", "kind": "header", "secret": True, "required": True, "template": "Bearer {value}",
             "about": "A restricted key (starts with rk_) from the Stripe dashboard with only the permissions Echo needs. Try a test-mode key first."},
        ],
        "steps": ["In the Stripe dashboard create a restricted key, read-only to start, and paste it when you approve."],
        "watch_out": [
            "Money moves through these tools: EchoSpeak asks before every action, and a read-only key is safest.",
            "Stripe is retiring older untagged restricted keys for its MCP server; create a new one if it's refused.",
        ],
        "verify": "Ask for the account balance (read-only).",
        "capability_policies": {},
        "homepage": "https://docs.stripe.com/mcp",
    },
    {
        "id": "hubspot",
        "app": "HubSpot",
        "field": "sales and CRM",
        "keywords": ["hubspot", "crm", "contacts", "deals", "sales", "leads"],
        "publisher": "community",
        "how": {"kind": "npm", "package": "@mindstone/mcp-server-hubspot", "registry": "io.github.mindstone/mcp-server-hubspot"},
        "needs": ["Node.js"],
        "settings": [],
        "steps": ["It needs a HubSpot private app token; the setup card lists the exact setting from the registry."],
        "watch_out": ["Give the private app only the scopes Echo needs."],
        "verify": "Search for one contact you know.",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.mindstone%2Fmcp-server-hubspot/versions/latest",
    },
    {
        "id": "notion",
        "app": "Notion",
        "field": "notes and team docs",
        "keywords": ["notion", "wiki", "docs", "pages", "database"],
        "publisher": "official (Notion)",
        "how": {"kind": "signin", "url": "https://mcp.notion.com/mcp"},
        "needs": [],
        "settings": [],
        "steps": ["Until sign-in is supported, community Notion servers that use an integration token show up when you search the registry for notion."],
        "watch_out": ["Notion's official server needs browser sign-in, which EchoSpeak doesn't support yet."],
        "verify": "",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/com.notion%2Fmcp/versions/latest",
    },
    {
        "id": "linear",
        "app": "Linear",
        "field": "project management",
        "keywords": ["linear", "issues", "tickets", "sprint", "project"],
        "publisher": "official (Linear)",
        "how": {"kind": "signin", "url": "https://mcp.linear.app/mcp"},
        "needs": [],
        "settings": [],
        "steps": [],
        "watch_out": ["Linear's official server needs browser sign-in, which EchoSpeak doesn't support yet."],
        "verify": "",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/app.linear%2Flinear/versions/latest",
    },
    {
        "id": "atlassian",
        "app": "Jira and Confluence",
        "field": "project management and team docs",
        "keywords": ["jira", "confluence", "atlassian", "tickets", "sprint", "wiki"],
        "publisher": "official (Atlassian)",
        "how": {"kind": "signin", "url": "https://mcp.atlassian.com/v2/mcp"},
        "needs": [],
        "settings": [],
        "steps": [],
        "watch_out": ["Atlassian's official server needs browser sign-in, which EchoSpeak doesn't support yet."],
        "verify": "",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/com.atlassian%2Fatlassian-mcp-server/versions/latest",
    },
    # ── home & personal ───────────────────────────────────────────────
    {
        "id": "obsidian",
        "app": "Obsidian",
        "field": "personal notes",
        "keywords": ["obsidian", "vault", "notes", "markdown"],
        "publisher": "built into EchoSpeak",
        "how": {"kind": "builtin", "where": "Settings > Connections > Obsidian"},
        "needs": [],
        "settings": [],
        "steps": ["Pick your vault folder in Settings > Connections > Obsidian."],
        "watch_out": [],
        "verify": "",
        "capability_policies": {},
        "homepage": "",
    },
    {
        "id": "home-assistant",
        "app": "Home Assistant",
        "field": "smart home",
        "keywords": ["home assistant", "smart home", "lights", "thermostat", "homeassistant", "devices"],
        "publisher": "community",
        "how": {"kind": "npm", "package": "@vortitron/home-assistant-mcp", "registry": "io.github.Vortitron/home-assistant-mcp"},
        "needs": ["Node.js", "A Home Assistant server you can reach"],
        "settings": [],
        "steps": [
            "In Home Assistant: your profile > Long-Lived Access Tokens > Create token.",
            "Paste the address and token in the settings the setup card lists.",
        ],
        "watch_out": ["The token can control every device Home Assistant exposes; EchoSpeak asks before device actions."],
        "verify": "Ask for the state of one light.",
        "capability_policies": {},
        "homepage": "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.Vortitron%2Fhome-assistant-mcp/versions/latest",
    },
]


def guide(guide_id: str) -> dict[str, Any] | None:
    return next((g for g in GUIDES if g["id"] == guide_id), None)
